version: 2
updates:
  - package-ecosystem: "submodules"
    directory: "/"  # Path to your `.gitmodules` file (use "/" if it's in the root)
    schedule:
      interval: "daily"  # Options: "daily", "weekly", "monthly"