version: 2
updates:
  - package-ecosystem: "gitsubmodule" 
    directory: "/"  # Path to your `.gitmodules` file (use "/" if it's in the root)
    schedule:
      interval: "weekly"  # Options: "daily", "weekly", "monthly"