name: build-install-AMGX-ada

env:
  AMGX_PATH: external/AMGX
  AMGX_CMAKE_OPTIONS: -DCUDA_ARCH=80 -DCMAKE_BUILD_TYPE=Release
  NICE_PRIORITY: 19
  NPROCS: 48
  MODULE_LIST: "cuda/12.8.0"  

on:
  push:
    branches: [ main ]
    paths:
      - 'external/AMGX/**'
      - '.github/workflows/build-install-AMGX-ada.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'external/AMGX/**'
      - '.github/workflows/build-install-AMGX-ada.yml'
  workflow_dispatch:  # allows manual triggering

jobs:
  build-install-AMGX-ada:
    runs-on: [self-hosted,ada]
    steps:
    - name: clone and checkout
      uses: actions/checkout@v3
      
    - name: get the AMGX submodule
      run: git submodule update --init --recursive ${{ env.AMGX_PATH }}

    - name: load modules
      run: |
        module purge
        module load $MODULES_TO_LOAD

    - name: reset build and configure
      working-directory: ${{ env.AMGX_PATH }}
      run: |
        [ -d build ] && rm -rf build
        cmake -B build -S . ${{ env.AMGX_CMAKE_OPTIONS }}

    - name: build AMGX 
      working-directory: ${{ env.AMGX_PATH }}
      run: |
        nice -n ${{ env.NICE_PRIORITY }} cmake --build build -- -j${{ env.NPROCS }}
    