name: build-test-AMGX-input-deck-ada

env:
  JOBPATH: build-AMGX-input-deck
  CMAKE_OPTIONS: "-DBUILD_MUELU_INPUT_DECK=OFF -DBUILD_AMGX_INPUT_DECK=ON -DBUILD_UNIT_TESTS=OFF"
  NICE_PRIORITY: 19
  NPROCS: 36
  MODULE_LIST: "cuda/12.8.0"

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build-test-AMGX-input-deck-ada.yml'
      #- '.github/workflows/build-install-AMGX-ada.yml'
      #- 'external/AMGX/**'
      - 'src/AMGX/**'
      - 'src/solver-market/**'
      - 'CMakeLists.txt'

  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/build-test-AMGX-input-deck-ada.yml'
      #- '.github/workflows/build-install-AMGX-ada.yml'
      #- 'external/AMGX/**'
      - 'src/AMGX/**'
      - 'src/solver-market/**'
      - 'CMakeLists.txt'


  workflow_dispatch:  # allows manual triggering

  workflow_run: #if the build of AMGX is triggered, this job will be too
    workflows: ["build-install-AMGX-ada"]
    types:
      - completed

jobs:
  build-AMGX-input-deck-ada:
    runs-on: [self-hosted, ada]

    steps:
    - name: clone and checkout
      uses: actions/checkout@v3

    - name: configure AMGX input deck
      run: |
        module purge
        module load ${{ env.MODULE_LIST }}
        [ -d $JOBPATH ] && rm -rf $JOBPATH
        cmake -B $JOBPATH -S . $CMAKE_OPTIONS

    - name: build AMGX input deck
      working-directory: ./$JOBPATH
      run: |
        module purge
        module load ${{ env.MODULE_LIST }}
        nice -n ${{ env.NICE_PRIORITY }}  make -j${{ env.NPROCS }}

    - name: run AMGX input deck test
      working-directory: ${{ env.JOBPATH }}
      run: |
        module purge
        module load ${{ env.MODULE_LIST }}
        nice -n $NICE_PRIORITY ./input-decks/AMGX_input_deck --matrix=../matrices/aij_51840.mtx --config=../external/AMGX/src/configs/PCG_V.json
