name: build-muelu-input-deck-ada

env:
  JOBPATH: build-muelu-input-deck
  CMAKE_OPTIONS: "-DBUILD_MUELU_INPUT_DECK=ON -DBUILD_AMGX_INPUT_DECK=OFF -DBUILD_UNIT_TESTS=OFF"
  NICE_PRIORITY: 19
  NPROCS: 48
  MODULE_LIST: "cuda/12.8.0"

on:
  push:
    branches: [ main ]
    JOBPATHs:
      - '.github/workflows/build-muelu-input-deck.yml'
      - '.github/workflows/build-install-trilinos-ada.yml'
      - 'external/trilinos/**'
      - 'src/muelu/**'
      - 'src/solver-market/**'
      - 'CMakeLists.txt'
  pull_request:
    branches: [ main ]
    JOBPATHs:
      - '.github/workflows/build-muelu-input-deck.yml'
      - '.github/workflows/build-install-trilinos-ada.yml'
      - 'external/trilinos/**'
      - 'src/muelu/**'
      - 'src/solver-market/**'
      - 'CMakeLists.txt'
  workflow_dispatch:
  workflow_run:
    workflows: ["build-install-trilinos-ada"]
    types:
      - completed

jobs:
  prepare-muelu-input-deck:
    runs-on: [self-hosted, ada]
    steps:
    - name: clone and checkout
      uses: actions/checkout@v3

    - name: load modules
        module load ${{ env.MODULE_LIST }}


    - name: check triggering context
      run: echo "Triggered by ${{ github.event_name }}"

  configure-muelu-input-deck:
    runs-on: [self-hosted, ada]
    needs: prepare-muelu-input-deck
    steps:
    - name: configure muelu input deck
      run: |
        [ -d $JOBPATH ] && rm -rf $JOBPATH
        cmake -B $JOBPATH -S . $CMAKE_OPTIONS

  build-muelu-input-deck:
    runs-on: [self-hosted, ada]
    needs: configure-muelu-input-deck
    steps:
    - name: build muelu input deck
      working-directory: ./$JOBPATH
      run: |
        nice -n $NICE_PRIORITY cmake --build . -- -j $NPROCS