name: build-install-trilinos-ada

env:
  JOBPATH: external/trilinos
  CMAKE_OPTIONS: -D Kokkos_ARCH_ADA89=ON
  NICE_PRIORITY: 19
  NPROCS: 48
  MODULE_LIST: "cuda/12.8.0"  
  SETUP_ENV: |
    module purge; \
    module load ${{ env.MODULE_LIST }}; \
    export WRAPPER_JOBPATH=${{ github.workspace }}/external/trilinos/install/packages/kokkos/bin/nvcc_wrapper; \
    export OMPI_CXX=$WRAPPER_JOBPATH; \
    export CXX=$WRAPPER_JOBPATH; \
    echo OMPI_CXX=$OMPI_CXX; \
    echo CXX=$CXX
  
on:
  push:
    branches: [ main ]
    JOBPATHs:
      - 'external/trilinos/**'
      - '.github/workflows/build-install-trilinos-ada.yml'

  pull_request:
    branches: [ main ]
    JOBPATHs:
      - 'external/trilinos/**'
      - '.github/workflows/build-install-trilinos-ada.yml'
  workflow_dispatch:  # allows manual triggering

jobs:
  build-install-trilinos-ada:
    runs-on: [self-hosted, ada]
    steps:

    - name: clone and checkout
      uses: actions/checkout@v3

    - name: Initialize and update trilinos submodule
      run: git submodule update --init --recursive ${{ env.JOBPATH }}
        

    - name: reset build and configure
      working-directory: ${{ env.JOBPATH }}
      run: |
        [ -d build ] && rm -rf build
        mkdir build
        [ -d install ] && rm -rf install
        mkdir install
        ${{ env.SETUP_ENV }}
        cmake -B build -S . \
        -D CMAKE_INSTALL_PREFIX=../install \
        -D CMAKE_BUILD_TYPE=RELEASE \
        -D BUILD_SHARED_LIBS:BOOL=ON \
        -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
        -D Trilinos_ENABLE_TESTS:BOOL=OFF \
        -D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
        -D Trilinos_ENABLE_MueLu:BOOL=ON \
        -D Kokkos_ENABLE_DEBUG=OFF \
        -D Kokkos_ENABLE_DEBUG_BOUNDS_CHECK=OFF \
        -D TPL_ENABLE_BLAS:BOOL=ON \
        -D TPL_ENABLE_MPI:BOOL=ON \
        -D TPL_ENABLE_CUSOLVER=ON \
        -D TPL_ENABLE_CUBLAS=ON \
        -D TPL_ENABLE_CUDA=ON \
        -D TPL_ENABLE_CUSPARSE=ON \
        -D MueLu_ENABLE_TESTS:BOOL=ON \
        -D MueLu_ENABLE_EXAMPLES:BOOL=ON \
        -D MueLu_ENABLE_CUSPARSE=ON \
        ${{ env.CMAKE_OPTIONS }}
        
    - name: build and install trilinos
      working-directory: ${{ env.JOBPATH }}
      run: |
        ${{ env.SETUP_ENV }}
        nice -n ${{ env.NICE_PRIORITY }} cmake --build build -- -j${{ env.NPROCS }}
        make install
    
