name: build-install-AMGX-ada

on:
  push:
    branches: [ main ]
    paths:
      - 'external/AMGX/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'external/AMGX/**'
  workflow_dispatch:  # allows manual triggering

jobs:
  build-install-AMGX-ada:
    runs-on: [self-hosted, ada]

    steps:
    - name: clone and checkout
      uses: actions/checkout@v3

    - name: Initialize and update MueLu submodule
      run: |
        git submodule update --init external/AMGX

    - name: load modules
      run: |
        module purge
        module load cuda/12.8.0
    
    - name: configure AMGX 
      working-directory: external/AMGX
      run: |
        mkdir build
        cd build 
        mkdir build && cd build
        cmake ..
          
    - name: build AMGX 
      working-directory: external/AMGX/build
      run: |
        nice -n 19 make -j48
    
    # - name: cache AMGX install
    #   uses: actions/cache@v3
    #   with:
    #     path: external/AMGX/install
    #     key: AMGX-install-ada

    # - name: cache AMGX build
    #   uses: actions/cache@v3
    #   with:
    #     path: external/AMGX/build
    #     key: AMGX-build-ada
