name: build-test-muelu-input-deck-ada

env:
  JOBPATH: build-test-muelu-input-deck
  CMAKE_OPTIONS: "-DBUILD_MUELU_INPUT_DECK=ON -DBUILD_AMGX_INPUT_DECK=OFF -DBUILD_UNIT_TESTS=OFF"
  NICE_PRIORITY: 19
  NPROCS: 48
  MODULE_LIST: "cuda/12.8.0"

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build-test-muelu-input-deck.yml'
      #- '.github/workflows/build-install-trilinos-ada.yml'
      #- 'external/trilinos/**'
      - 'src/muelu/**'
      - 'src/solver-market/**'
      - 'CMakeLists.txt'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/build-test-muelu-input-deck.yml'
      #- '.github/workflows/build-install-trilinos-ada.yml'
      #- 'external/trilinos/**'
      - 'src/muelu/**'
      - 'src/solver-market/**'
      - 'CMakeLists.txt'
  workflow_dispatch:
  
  #if the build of trilinos is triggered, this job will be too, after
  #This is why the two elements are commented above
  workflow_run:
    workflows: ["build-install-trilinos-ada"]
    types:
      - completed

jobs:
  build-test-muelu-input-deck-ada:
    runs-on: [self-hosted, ada]
    steps:
    
    - name: clone and checkout
      uses: actions/checkout@v3

    - name: configure muelu input deck
      run: |
        module purge
        module load ${{ env.MODULE_LIST }}
        [ -d $JOBPATH ] && rm -rf $JOBPATH
        cmake -B $JOBPATH -S . $CMAKE_OPTIONS

    - name: build muelu input deck
      working-directory: ${{ env.JOBPATH }
      run: |
        module purge
        module load ${{ env.MODULE_LIST }}
        nice -n ${{ env.NICE_PRIORITY }}  make -j${{ env.NPROCS }}
