name: build-install-AMGX-ada

env:
  JOBPATH: external/AMGX
  AMGX_CMAKE_OPTIONS: -DCUDA_ARCH=80 -DCMAKE_BUILD_TYPE=Release
  NICE_PRIORITY: 19
  NPROCS: 48
  MODULE_LIST: "cuda/12.8.0"  

on:
  push:
    branches: [ main ]
    paths:
      - 'external/AMGX/**'
      - '.github/workflows/build-install-AMGX-ada.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'external/AMGX/**'
      - '.github/workflows/build-install-AMGX-ada.yml'
  
  workflow_dispatch:  # allows manual triggering

jobs:
  build-install-AMGX-ada:
    runs-on: [self-hosted,ada]
    steps:
    - name: clone and checkout
      uses: actions/checkout@v3
      
    - name: get the AMGX submodule
      run: git submodule update --init --recursive ${{ env.JOBPATH }}

    - name: reset build and configure
      working-directory: ${{ env.JOBPATH }}
      run: |
        module purge
        module load ${{ env.MODULE_LIST }}
        [ -d build ] && rm -rf build
        cmake -B build -S . ${{ env.AMGX_CMAKE_OPTIONS }}

    - name: build AMGX 
      working-directory: ${{ env.JOBPATH }}/build
      run: |
        module purge
        module load ${{ env.MODULE_LIST }}
        nice -n ${{ env.NICE_PRIORITY }}  make -j${{ env.NPROCS }}
    