name: build-install-AMGX-ada
 
on:
  push:
    branches: [ main ]
    paths:
      - 'external/AMGX/**'
      - '.github/workflows/build-install-AMGX-ada.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'external/AMGX/**'
      - '.github/workflows/build-install-AMGX-ada.yml'
  workflow_dispatch:  # allows manual triggering

jobs:
  prepare-AMGX:
    runs-on: [self-hosted, ada]
    steps:
    - name: clone and checkout
      uses: actions/checkout@v3
    - name: Initialize and update AMGX submodule
      run: |
        git submodule update --init --recursive external/AMGX
    - name: load modules
      run: |
        module purge
        module load cuda/12.8.0
    - name: reset build and install 
      working-directory: external/trilinos
      run: |
        [ -d build ] && rm -rf build
        mkdir build

  configure-AMGX:
    runs-on: [self-hosted, ada]
    needs: prepare-AMGX
    steps:  
    - name: configure AMGX 
      working-directory: external/AMGX/build
      run: |
        cmake -DCUDA_ARCH="80" ..
    
  build-AMGX:
    runs-on: [self-hosted, ada]
    needs: configure-AMGX
    steps:  
    - name: build AMGX 
      working-directory: external/AMGX/build
      run: |
        nice -n 19 make -j48
    
    # - name: cache AMGX install
    #   uses: actions/cache@v3
    #   with:
    #     path: external/AMGX/install
    #     key: AMGX-install-ada

    # - name: cache AMGX build
    #   uses: actions/cache@v3
    #   with:
    #     path: external/AMGX/build
    #     key: AMGX-build-ada
