name: unit-test-solver-market-csr-matrix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-test-solver-market-csr-matrix:
    runs-on: ubuntu-latest

    steps:
    - name: clone and checkout
      uses: actions/checkout@v3

    - name: create build
      run: mkdir build

    - name: Configure 
      working-directory: ./build
      run: |
        cmake .. -DBUILD_MUELU_INPUT_DECK=OFF -DBUILD_AMGX_INPUT_DECK=OFF -DBUILD_UNIT_TESTS=ON

    - name: build
      working-directory: ./build
      run: make -j2

    - name: test
      working-directory: ./build/tests
      run: ./unit-test-solver-market-csr-matrix
