name: unit-test-solver-market-reader
  
on:
  push:
    branches: [ main ]
    paths:
     - 'src/solver-market'
     - 'CMakeLists.txt'
     - '.github/workflows/unit-test-solver-market-reader.yml'

  pull_request:
    branches: [ main ]
    paths:
      - 'src/solver-market'
      - 'CMakeLists.txt'
      - '.github/workflows/unit-test-solver-market-reader.yml'
jobs:
  unit-test-solver-market-csr-matrix:
    runs-on: ubuntu-latest

    steps:
    - name: clone and checkout
      uses: actions/checkout@v3

    - name: Initialize and update trilinos submodule
      run: |
        git submodule update --init --recursive external/trilinos
    - name: load modules
      run: |
        export WRAPPER_PATH="${{ github.workspace }}/external/trilinos/packages/kokkos/bin/nvcc_wrapper"
        export OMPI_CXX=$WRAPPER_PATH
        export CXX=$WRAPPER_PATH
        echo "OMPI_CXX=$OMPI_CXX"
        echo "CXX=$CXX"

    - name: reset build and install for trilinos
      working-directory: external/trilinos
      run: |
        [ -d build ] && rm -rf build
        mkdir build
        [ -d install ] && rm -rf install
        mkdir install

    - name: configure trilinos in debug mode, for kokkos only
      working-directory: external/trilinos/build
      run: |
        cmake \
        -D CMAKE_INSTALL_PREFIX=../install \
        -D BUILD_SHARED_LIBS:BOOL=ON \
        -D CMAKE_BUILD_TYPE=DEBUG \
        -D Trilinos_ENABLE_Kokkos=ON \
        -D Kokkos_ENABLE_DEBUG=ON \
        -D Kokkos_ENABLE_DEBUG_BOUNDS_CHECK=ON \
        ..

    - name: install trilinos, kokkos only
      working-directory: external/trilinos/build
      run: |
        nice -n 19 make -j48
        make install

    - name: create build
      run: mkdir build

    - name: Configure 
      working-directory: ./build
      run: |
        cmake .. -DBUILD_MUELU_INPUT_DECK=OFF -DBUILD_AMGX_INPUT_DECK=OFF -DBUILD_UNIT_TESTS=ON

    - name: build
      working-directory: ./build
      run: make -j2

    - name: test
      working-directory: ./build/tests
      run: ./unit-test-solver-market-reader
